name: Push
permissions:
  contents: write
  actions: write

on:
  push:
    branches: ["android12-5.10-lts"]
  pull_request:
    branches: ["android12-5.10-lts"]

jobs:
  build:
    uses: bachnxuan/android12-5.10-lts/.github/workflows/builder.yml@main
    with:
      ref: ${{ github.ref_name }}
    secrets: inherit
